
-- ============================================
-- Customer Shopping Behavior Analysis
-- SQL Queries for Business Intelligence
-- ============================================
-- 
-- This file contains analytical queries for understanding customer behavior,
-- segmentation, and business performance metrics.
--
-- Database: PostgreSQL
-- Table: customer
--
-- Usage: psql -U postgres -d customer_behavior -f customer_behavior_sql_queries.sql
-- ============================================

-- Q1. What is the total revenue generated by male vs. female customers?
-- Purpose: Understand gender-based purchasing patterns for targeted marketing
SELECT gender, 
       SUM(purchase_amount) as revenue,
       COUNT(*) as transaction_count,
       ROUND(AVG(purchase_amount), 2) as avg_purchase
FROM customer
GROUP BY gender
ORDER BY revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Purpose: Identify high-value customers who respond to promotions
SELECT customer_id, 
       purchase_amount,
       (SELECT ROUND(AVG(purchase_amount), 2) FROM customer) as overall_avg
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
-- Purpose: Identify best-performing products for promotion and inventory planning
SELECT item_purchased, 
       ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating",
       COUNT(*) as total_purchases
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

-- 11. Identify customer distribution by churn risk category.
SELECT
    churn_risk_flag,
    COUNT(*) AS customer_count
FROM customer
GROUP BY churn_risk_flag;


-- 12. Analyze churn risk across machine learning–based customer segments.
SELECT
    customer_segment_name,
    churn_risk_flag,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment_name, churn_risk_flag
ORDER BY customer_segment_name;


-- 13. Calculate average purchase frequency for each customer segment.
SELECT
    customer_segment_name,
    ROUND(AVG(purchase_frequency_days), 2) AS avg_purchase_frequency_days
FROM customer
GROUP BY customer_segment_name;


-- 14. Measure revenue contribution of each customer segment for waterfall analysis.
SELECT
    customer_segment_name,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY customer_segment_name
ORDER BY total_revenue DESC;


-- 15. Compute total revenue at risk due to high churn customers.
SELECT
    SUM(purchase_amount) AS revenue_at_risk
FROM customer
WHERE churn_risk_flag = 'High';


-- 16. Extract high-risk customer details for retention planning.
SELECT
    customer_id,
    customer_segment_name,
    purchase_amount,
    purchase_frequency_days
FROM customer
WHERE churn_risk_flag = 'High';

